{% set version = "4.27" %}

package:
  name: nspr
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/nspr/releases/v{{ version }}/src/nspr-{{ version }}.tar.gz
  sha256: 6d495192b6ab00a3c28db053492cf794329f7c0351a5728db198111a1816e89b

build:
  number: 1
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - sed

test:
  commands:
    - test -f ${PREFIX}/lib/libnspr4${SHLIB_EXT}         # [unix]
    - test -f ${PREFIX}/lib/libplc4${SHLIB_EXT}          # [unix]
    - test -f ${PREFIX}/lib/libplds4${SHLIB_EXT}         # [unix]
    - test -d ${PREFIX}/include/nspr                     # [unix]
    - test -f ${PREFIX}/bin/nspr-config                  # [unix]

about:
  home: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
  license: MPL-2.0
  license_file: nspr/LICENSE
  summary: A platform-neutral API for system level and libc-like functions.
  description: |
    NetScape Portable Runtime (NSPR) provides platform independence for
    non-GUI operating system facilities. These facilities include threads,
    thread synchronization, normal file and network I/O, interval timing and
    calendar time, basic memory management (malloc and free) and shared
    library linking.
  doc_url: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
  dev_url: https://developer.mozilla.org/en-US/docs/MDN

extra:
  recipe-maintainers:
    - marcelotrevisani
    - jakirkham
