# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HYibEhI4t76Xl6qQeNVE+O5s/XCNS2JjmyxzvkrHA037BSY5L+0NLjKqUiol2NheYjXaIQx2/xVCAi90/hp6CquI+M5hTb5eWndgjx26XHnzWTrInbOQ/qSEwlHvqMHdh+QG/R6/TcfXo739DfMgjnAPlsQyudKSgfp46P7bO4z4/wQ+USWxSp5KwHANAEAwsysVRR74+C7W8apB/tkPNPq093fCaXkW1ZFBRWglGrH5TRvnLnA4MXi9pCgbUmeHZUJRJTmU1MOQEZD3g+isro/OO2+4I45EHFQdD3yU/wdS1RtQCmQeWevxzlWvSCI4TN/rJpu/dE+Yq/nJ54vCSeBqM85mPvMXMkdRBzRq+JxtNMcZS5fQYLIOYRENUallFynejQLB++eRely8CLzgA4ySZxj/TyvsdfpIlyF5kRiJraZjfMLj53T4nJr90MrLeqZlsjFwTnZS4MD9Q9l9uDOs0lg4eJssamsdL8MIvwjWHo1j4c6YO7iVe8fzce0mH38v85GntB02ftOdbCz6OiqesQswuxbsEAuUb8uC8deqE2N960DM1BRPKDFzcMYcZrfio6E+14l4XG5uOof0hLJoWlwkjdPpOvrHDu9xnFdfFPikXPwvQWH7zwoHiK6LUStAeR2C6vQjEUQL+Sh5CMQEkPo+9Cq+YiV1ZA9hFkk="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.travis/run_docker_build.sh; fi